spring.application.name=SpringAiLearning
server.port=9091
# Google
spring.ai.google.genai.embedding.api-key={GOOGLE_API_KEY}
spring.ai.google.genai.api-key={GOOGLE_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.6-flash
spring.ai.google.genai.embedding.text.model=gemini-embedding-2
spring.ai.google.genai.embedding.text.dimensions=1536

# Chat model
spring.ai.openai.chat.options.model=gpt-4.1-mini

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1536